- hosts: all
  roles:
    - role: dotfiles
      tags: dotfiles
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: packages
      tags: packages
    - role: settings
      tags: settings
