---
- name: Install packages
  homebrew:
    name:
      - aria2
      - fzf
      - gawk
      - gpg
      - helm
      - kubectl
      - lastpass-cli
      - neovim
      - nodejs
      - sops
      - tfenv
      - tmux
      - awscli
      - azure-cli

- name: Tap cask
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install casks
  homebrew_cask:
    name: "{{ item }}"
  loop:
    - docker
    - font-sauce-code-pro-nerd-font
    - iterm2
    - karabiner-elements
    - lens
    - puppetlabs/puppet/pdk
    - puppetlabs/puppet/pe-client-tools
    - puppetlabs/puppet/puppet-agent
    - puppetlabs/puppet/puppet-bolt
    - vagrant
    - virtualbox
    - visual-studio-code
