---

- name: Install packages
  become: yes
  macports:
    name:
      - alacritty
      - aria2
      - fzf
      - go
      - neovim
      - nnn
      - npm6
      - ripgrep
      - tmux

- name: Install Nerd Fonts
  become: yes
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/SourceCodePro.zip
    dest: /Library/Fonts
    remote_src: yes
