---

- name: Install packages
  homebrew:
    name:
      - aria2
      - awscli
      - azure-cli
      - fzf
      - gawk
      - gpg
      - helm
      - kubectl
      - neovim
      - nodejs
      - pipenv
      - sops
      - terragrunt
      - tfenv
      - tmux

- name: Install casks
  homebrew_cask:
    name:
      - alacritty
      - docker
      - homebrew/cask-fonts/font-sauce-code-pro-nerd-font
