---

- name: Install packages
  homebrew:
    name:
      - aria2
      - awscli
      - azure-cli
      - bitwarden-cli
      - fzf
      - gawk
      - gpg
      - helm
      - k3d
      - kubectl
      - neovim
      - nnn
      - nodejs
      - pipenv
      - ripgrep
      - sops
      - tfenv
      - tmux
      - tree

- name: Install casks
  homebrew_cask:
    name:
      - alacritty
      - bitwarden
      - docker
      - firefox
      - homebrew/cask-fonts/font-fira-code-nerd-font
      - karabiner-elements
      - multipass
      - visual-studio-code
