---

- name: Install packages
  homebrew:
    name:
      - aria2
      - awscli
      - azure-cli
      - bitwarden-cli
      - fzf
      - gawk
      - go
      - gpg
      - helm
      - k3d
      - kubectl
      - neovim
      - nnn
      - nodejs
      - pipenv
      - ripgrep
      - sops
      - tfenv
      - tmux
      - tree

- name: Install casks
  homebrew_cask:
    name:
      - alacritty
      - brave-browser
      - docker
      - homebrew/cask-fonts/font-fira-code-nerd-font
      - karabiner-elements
      - vagrant
      - virtualbox
      - viscosity
