- name: Install packages
  homebrew:
    name:
      - aria2
      - awscli
      - azure-cli
      - bat
      - bitwarden-cli
      - fzf
      - gawk
      - gh
      - go
      - gpg
      - helm
      - k3d
      - kubectl
      - kustomize
      - neovim
      - nnn
      - nodejs
      - pipenv
      - ripgrep
      - sops
      - tfenv
      - tmux
      - translate-shell
      - tree

- name: Install casks
  homebrew_cask:
    name:
      - alacritty
      - bitwarden
      - docker
      - gswitch
      - homebrew/cask-fonts/font-fira-code-nerd-font
      - karabiner-elements
      - macs-fan-control
      - vagrant
      - virtualbox
      - viscosity
