- name: Install packages
  homebrew:
    name:
      - aria2
      - bat
      - coreutils
      - fzf
      - gawk
      - gh
      - go
      - gpg
      - helm
      - jq
      - kubectl
      - kustomize
      - moreutils
      - neovim
      - nnn
      - nodejs
      - ripgrep
      - sops
      - tfenv
      - tmux
      - translate-shell
      - tree
      - watch
      - wget
      - yarn
      - zoxide

- name: Install casks
  homebrew_cask:
    name:
      - alacritty
      - homebrew/cask-fonts/font-fira-code-nerd-font
      - macs-fan-control

- name: Create missing directories for config files
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.config/alacritty"
    - "~/.config/karabiner"

- name: Copy macOS specific config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: alacritty.yml
      dest: ~/.config/alacritty/alacritty.yml
    - src: karabiner.json
      dest: ~/.config/karabiner/karabiner.json
