---
- name: Install packages
  homebrew:
    name:
      - fzf
      - neovim
      - nodejs
      - terraform
      - tmux

- name : Install terminal
  homebrew_cask:
    name: iterm2

- name: Add Homebrew Cask Fonts
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install font
  homebrew_cask:
    name: font-sauce-code-pro-nerd-font

- name: Install Karabiner
  homebrew_cask:
    name: karabiner-elements

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

- name: Install others
  homebrew_cask:
    name: "{{ item }}"
  loop:
    - puppetlabs/puppet/puppet-bolt
