---

- name: Install packages
  homebrew:
    name:
      - alacritty
      - aria2
      - fzf
      - gawk
      - gpg
      - helm
      - kubectl
      - neovim
      - nodejs
      - pipenv
      - sops
      - tfenv
      - tmux
      - awscli
      - azure-cli

- name: Tap cask
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install casks
  homebrew_cask:
    name: "{{ item }}"
  loop:
    - docker
    - font-sauce-code-pro-nerd-font
    - karabiner-elements
    - visual-studio-code
