---

- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "~"

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "~"
    value: "no"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "~"
  register: add_remote
  failed_when: add_remote.rc != 0 and "already exist" not in add_remote.stderr

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "~"
    update: yes

- name: Create missing directories for config files
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.config/alacritty"
    - "~/.config/karabiner"

- name: Link Alacritty config file
  file:
    src: "{{ role_path }}/files/alacritty.yml"
    dest: "~/.config/alacritty/alacritty.yml"
    state: link

- name: Link Karabiner config file
  file:
    src: "{{ role_path }}/files/karabiner.json"
    dest: "~/.config/karabiner/karabiner.json"
    state: link

- name: Link yabai config file
  file:
    src: "{{ role_path }}/files/yabairc"
    dest: "~/.yabairc"
    state: link

- name: Link skhd config file
  file:
    src: "{{ role_path }}/files/skhdrc"
    dest: "~/.skhdrc"
    state: link

- name: Start services
  command: "brew services start {{ item }}"
  loop:
    - yabai
    - skhd
