---

- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "{{ home }}"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "{{ home }}"
  register: add_remote
  failed_when: add_remote.rc != 0 and add_remote.rc != 128

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ home }}"
    update: yes

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "{{ home }}"
    value: "no"

- name: Install VS Code extensions
  loop: "{{ lookup('file', '{{ home }}/.config/Code - OSS/User/extensions.txt').splitlines() }}"
  command: "code --install-extension {{ item }}"

- name: Link VS Code config file to fit macOS
  file:
    src: "{{ home }}/.config/Code - OSS/User/settings.json"
    dest: "{{ home }}/Library/Application\ Support/Code/User/settings.json"
    state: link
