---

- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "~"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "~"
  register: add_remote
  failed_when: add_remote.rc != 0 and add_remote.rc != 128

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "~"
    update: yes

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "~"
    value: "no"

- name: Copy Alacritty config file
  copy:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml

- name: Copy Karabiner config file
  copy:
    src: karabiner.json
    dest: ~/.config/karabiner/karabiner.json

- name: Install VS Code extensions
  loop: "{{ lookup('file', '~/.config/Code - OSS/User/extensions.txt').splitlines() }}"
  command: "code --install-extension {{ item }}"

- name: Link VS Code config file to fit macOS
  file:
    src: "~/.config/Code - OSS/User/settings.json"
    dest: "~/Library/Application Support/Code/User/settings.json"
    state: link
