---
- name: Clone dotfiles repository
  git:
    repo: "https://github.com/khuedoan/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"

- name: Create config directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .config
    - .config/nvim
    - .config/tmux

- name: Link config files
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  loop:
    - .zshrc
    - .zsh
    - .zshenv
    - .aliases
    - .hushlogin
    - .p10k.zsh
    - .config/nvim/init.vim
    - .config/nvim/coc-settings.json
    - .config/tmux/tmux.conf
