---

- name: Download
  get_url:
    url: https://github.com/pqrs-org/Karabiner-Elements/releases/download/v13.1.0/Karabiner-Elements-13.1.0.dmg
    dest: /tmp/Karabiner-Elements.dmg

- name: Attach the installer
  command:
    cmd: hdiutil attach /tmp/Karabiner-Elements.dmg

- name: Install
  become: yes
  command:
    cmd: installer -package /Volumes/Karabiner-Elements-13.1.0/Karabiner-Elements.pkg -target LocalSystem
    creates: /Applications/Karabiner-Elements.app

- name: Detach the installer
  command:
    cmd: hdiutil detach /Volumes/Karabiner-Elements-13.1.0

- name: Allow Karabiner to monitor input
  osx_defaults:
    domain: com.apple.universalaccessAuthWarning
    key: "{{ item }}"
    value: 1
  loop:
   - "2::/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber"
   - "2::/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer"
