---

- name: Download Karabiner
  get_url:
    url: https://github.com/pqrs-org/Karabiner-Elements/releases/download/v13.1.0/Karabiner-Elements-13.1.0.dmg
    dest: /tmp/Karabiner-Elements.dmg

- name: Mount the Karabiner installer
  command:
    cmd: hdiutil attach /tmp/Karabiner-Elements.dmg

- name: Install Karabiner
  become: yes
  command:
    cmd: installer -package /Volumes/Karabiner-Elements-13.1.0/Karabiner-Elements.pkg -target LocalSystem
    creates: /Applications/Karabiner-Elements.app/Contents/PkgInfo

- name: Detach the Karabiner installer
  command:
    cmd: hdiutil detach /Volumes/Karabiner-Elements-13.1.0

- name: Allow Karabiner to monitor input
  osx_defaults:
    domain: com.apple.universalaccessAuthWarning
    key: "{{ item }}"
    type: bool
    value: 1
  loop:
   - "2::/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber"
   - "2::/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer"

- name: Install Visual Studio Code
  unarchive:
    src: "https://code.visualstudio.com/sha/download?build=stable&os=darwin"
    dest: ~/Applications
    remote_src: yes
    creates: ~/Applications/Visual Studio Code.app/Contents/PkgInfo

- name: Link Visual Studio Code binary
  file:
    src: "~/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    dest: "~/.local/bin/code"
    state: link
