---

- name: Automatically hide and show the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: 1

- name: Put the Docker on the left
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left

- name: Disable automatically rearrange Spaces
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: 0

- name: Reload Dock
  command:
    cmd: killall Dock
